[project]
name = "mcp-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kirthi0071", email = "kirthikumar077@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=2.0.0",
]

[project.scripts]
mcp-test = "mcp_test:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
